"""Shared defaults for printed color segments and slicer layers (millimetres)."""
DEFAULT_FILAMENT_PRESET = "bambu_cmywk"
DEFAULT_BACKING_LAYERS = 3
MAX_COLOR_LAYERS = 10
REGULAR_LAYER_HEIGHT_MM = 0.08
TRANSPARENT_SLICER_LAYER_HEIGHT_MM = 0.28
TRANSPARENT_SLICER_LAYERS_PER_COLOR = 3
# Rounded so the float product serializes as 0.84, not 0.8400000000000001.
TRANSPARENT_LAYER_HEIGHT_MM = round(TRANSPARENT_SLICER_LAYER_HEIGHT_MM * TRANSPARENT_SLICER_LAYERS_PER_COLOR, 6)
